### ISSUE TITLE
When I start my bot using npm start this happens.

### ISSUE THREAD

**Issue by iamnoob6969** [Allvaa/lavalink-musicbot#139]
```
/bot4/src/structures/MusicClient.js:32
        this.prefix = process.env.PREFIX.toLowerCase();
                                         ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at new MusicClient (/bot4/src/structures/MusicClient.js:32:42)
    at Object.<anonymous> (/bot4/src/bot.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/bot4/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

```

**Comment by Allvaa** [comment]
have you fill the .env yet?
