### ISSUE TITLE
question helppppp pls *lavasfy, sc*

### ISSUE THREAD

**Issue by sarabano1** [Allvaa/lavalink-musicbot#152]
this.player
            .on("start", () => {
                this.current = this.queue.shift();
                if (this.textChannel) this.textChannel.send(util.embed().setcolor (message.guild.me.display.HexColor).setDescription(`🎶 | Now playing **${this.current.info.title}**.`));
            }) 
            
embed color same as topest role 
how can i define message in this music handler

**Comment by rajamoulimallareddy** [comment]
> ```
>     this.player
>         .on("start", () => {
>             this.current = this.queue.shift();
>             if (this.textChannel) this.textChannel.send(util.embed().setcolor (message.guild.me.display.HexColor).setDescription(`🎶 | Now playing **${this.current.info.title}**.`));
>         }) 
> ```
> 
> embed color same as topest role
> how can i define message in this music handler

```js
this.player
.on("start", () => {
    this.current = this.queue.shift();
    if (this.textChannel) this.textChannel.send(util.embed().setColor(this.guild.me.displayHexColor).setDescription(`🎶 | Now playing **${this.current.info.title}**.`));
})

**Comment by sarabano1** [comment]
thx worked sry to asking again how can i add current playing music link to the description message in this result message 
[ ${this.current.info.title} ]

**Comment by rajamoulimallareddy** [comment]
> thx worked sry to asking again how can I add current playing music link to the description message in this result message [ ${this.current.info.title} ]

If you are talking about URL then ` [${this.current.info.title}](${this.current.info.uri})`

**Comment by sarabano1** [comment]
and how can i mention after [${this.current.info.title}](${this.current.info.uri}) in [mention]

like "SONG NAME" requested by [@rajamoulimallareddy#0 0 0 1]

**Comment by rajamoulimallareddy** [comment]
> and how can i mention after [${this.current.info.title}]($%7Bthis.current.info.uri%7D) in [mention]
> 
> like "SONG NAME" requested by [@rajamoulimallareddy#0 0 0 1]

keep like ${this.current.requester} or ${this.current.requester.tag} .....

**Comment by sarabano1** [comment]
ur the god thank a lot
do i can add another aliases for like skip command ? exept skip and skipto like -n

**Comment by sarabano1** [comment]
and another think i want -n has another reaction emoji for variety how How can i do this ? 
example = -skip 👌 -n 🤙  but do same thing

**Comment by sarabano1** [comment]
and i wanna now playing message get deleted when current music ended 

sry i ask so many question together ♥♥♥♥
3 question right now

**Comment by yofukashino** [comment]
> and i wanna now playing message get deleted when current music ended
> 
> sry i ask so many question together ♥♥♥♥ 3 question right now

the pull request is there #156 check it

**Comment by yofukashino** [comment]
> ur the god thank a lot do i can add another aliases for like skip command ? exept skip and skipto like -n

well just add it in the command file in` aliases: ['skip' ,'skipto', '-n'],` this should do it

**Comment by yofukashino** [comment]
> and another think i want -n has another reaction emoji for variety how How can i do this ? example = -skip 👌 -n 🤙 but do same thing

well check for the message content and if use message react to react to message

**Comment by sarabano1** [comment]
> the pull request is there #156 check it

i dont get it  what i need to do ?

is this.player.msg a thing

Tharki-God commented 9 days ago
Well i defined it as the now playing message.

**Comment by sarabano1** [comment]
can some one answer my questions in discord ?

**Comment by rajamoulimallareddy** [comment]
> can some one answer my questions in discord ?
Join here
https://discord.gg/K9BnjfEwqy

**Comment by hapoow** [comment]
> > the pull request is there #156 check it
> 
> i dont get it what i need to do ?
> 
> is this.player.msg a thing
> 
> Tharki-God commented 9 days ago Well i defined it as the now playing message.

how can i define this.player.msg

**Comment by yofukashino** [comment]
> can some one answer my questions in discord ?

[My Discord ID](https://discord.com/users/887483349369765930), send a friend request

**Comment by yofukashino** [comment]
> > the pull request is there #156 check it
> 
> i dont get it what i need to do ?
> 
> is this.player.msg a thing
> 
> Tharki-God commented 9 days ago Well i defined it as the now playing message.

just add the code defined in pull request

**Comment by sarabano1** [comment]
![Screenshot 2021-10-24 004459](https://user-images.githubusercontent.com/91519759/138571833-ff03a473-ecbe-49c9-9a07-be07b79b1be1.png)
how can i fix this ?
\
\
\
lava link eror :

> 2021-10-24 00:31:27.042 ERROR 10716 --- [ader-2-thread-5] l.server.player.AudioLoaderRestHandler   : Track loading failed

>com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
        at >com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-1.3.76.jar!/:na]
        at >com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.3.76.jar!/:na]
        at >com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.76.jar!/:na]
        at >com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.76.jar!/:na]
        at >com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.76.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.76
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 11
  java.runtime.version: 11+28
  java.vm.version: 11+28

i want soundcloud tooooooooooooooooooooo

**Comment by rajamoulimallareddy** [comment]
> ![Screenshot 2021-10-24 004459](https://user-images.githubusercontent.com/91519759/138571833-ff03a473-ecbe-49c9-9a07-be07b79b1be1.png) how can i fix this ? lava link eror :
> 
> > 2021-10-24 00:31:27.042 ERROR 10716 --- [ader-2-thread-5] l.server.player.AudioLoaderRestHandler   : Track loading failed
> 
> > com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
> > at >com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-1.3.76.jar!/:na]
> > at >com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.3.76.jar!/:na]
> > at >com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.76.jar!/:na]
> > at >com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.76.jar!/:na]
> > at >com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.76.jar!/:na]
> > at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
> > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
> > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
> > at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
> > Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
> > lavaplayer.version: 1.3.76
> > os.arch: amd64
> > os.name: Windows 10
> > os.version: 10.0
> > java.vendor: Oracle Corporation
> > java.version: 11
> > java.runtime.version: 11+28
> > java.vm.version: 11+28
> 
> i want soundcloud tooooooooooooooooooooo

show your lavafy options

**Comment by sarabano1** [comment]
### default lavafy config @rajamoulimallareddy 

**8888888888888888888888888888888888888888888888888888888888888888888888**


const { Manager } = require("@lavacord/discord.js");
const { Client, Collection } = require("discord.js");
const { promises: { readdir } } = require("fs");
const { join } = require("path");
const { LavasfyClient } = require("lavasfy");

require("../extensions");

module.exports = class MusicClient extends Client {
    /** @param {import("discord.js").ClientOptions} [opt] */
    constructor(opt) {
        super(opt);
        this.commands = new Collection();
        this.manager = new Manager(this, [
            {
                id: "main",
                host: process.env.LAVA_HOST,
                port: process.env.LAVA_PORT,
                password: process.env.LAVA_PASS
            }
        ]);
        this.spotify = process.env.ENABLE_SPOTIFY === "true"
            ? new LavasfyClient({
                clientID: process.env.SPOTIFY_ID,
                clientSecret: process.env.SPOTIFY_SECRET,
                playlistLoadLimit: process.env.SPOTIFY_PLAYLIST_PAGE_LIMIT,
                audioOnlyResults: true,
                useSpotifyMetadata: true
            }, [...[...this.manager.nodes.values()]])
            : null;

        this.prefix = process.env.PREFIX.toLowerCase();
    }

    build() {
        this.loadCommands();
        this.loadEventListeners();
        this.login(process.env.TOKEN);

        this.manager
            .on("ready", node => console.log(`Node ${node.id} is ready!`))
            .on("disconnect", (ws, node) => console.log(`Node ${node.id} disconnected.`))
            .on("reconnecting", (node) => console.log(`Node ${node.id} tries to reconnect.`))
            .on("error", (error, node) => console.log(`Node ${node.id} got an error: ${error.message}`));
    }

    /** @private */
    async loadCommands() {
        const commands = await readdir(join(__dirname, "..", "commands"));
        for (const commandFile of commands) {
            const command = require(`../commands/${commandFile}`);
            this.commands.set(command.name, command);
        }
    }

    /** @private */
    async loadEventListeners() {
        const listeners = await readdir(join(__dirname, "..", "listeners"));
        for (const listenerFile of listeners) {
            const listener = require(`../listeners/${listenerFile}`);
            this.on(listener.name, (...args) => listener.exec(this, ...args));
        }
    }
};

**8888888888888888888888888888888888888888888888888888888888888888888888**

this is music client.js 
its default as this https://github.com/Allvaa/lavalink-musicbot/blob/master/src/structures/MusicClient.js

**Comment by yofukashino** [comment]
you need to set auto resolve

**Comment by sarabano1** [comment]
> you need to set auto resolve

what ?? how? where exacly musicclient which line

**Comment by Allvaa** [comment]
> how can i fix this ? lava link eror :
> 
> > 2021-10-24 00:31:27.042 ERROR 10716 --- [ader-2-thread-5] l.server.player.AudioLoaderRestHandler   : Track loading failed
> 
> > com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
> > at >com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-1.3.76.jar!/:na]
> > at >com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.3.76.jar!/:na]
> > at >com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.76.jar!/:na]
> > at >com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.76.jar!/:na]
> > at >com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.76.jar!/:na]
> > at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
> > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
> > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
> > at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
> > Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
> > lavaplayer.version: 1.3.76
> > os.arch: amd64
> > os.name: Windows 10
> > os.version: 10.0
> > java.vendor: Oracle Corporation
> > java.version: 11
> > java.runtime.version: 11+28
> > java.vm.version: 11+28
> 
> i want soundcloud tooooooooooooooooooooo


update your lavalink.jar

**Comment by sarabano1** [comment]
![unknown 1](https://user-images.githubusercontent.com/91519759/146873861-3c2250ff-21a3-4e84-92cb-364fca8b5fd3.png)
 has some problem with artist play option
https://open.spotify.com/artist/belabelabela something like this with artist slash does not work
