### ISSUE TITLE
huh !

### ISSUE THREAD

**Issue by ig4e** [Allvaa/lavalink-musicbot#4]
Bot is online!
events.js:180
    throw err; // Unhandled 'error' event
    ^
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at PlayerManager.emit (events.js:178:17)
    at LavalinkNode.onError (/rbd/pnpm-volume/3be8f7c0-b853-4d2e-877b-e447f674a5b7/node_modules/.registry.npmjs.org/discord.js-lavalink/3.0.0/node_modules/discord.js-lavalink/dist/lib/LavalinkNode.js:71:22)
    at WebSocket.emit (events.js:189:13)
    at ClientRequest.req.on (/rbd/pnpm-volume/3be8f7c0-b853-4d2e-877b-e447f674a5b7/node_modules/.registry.npmjs.org/ws/7.2.3/node_modules/ws/lib/websocket.js:555:15)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Allvaa** [comment]
does the error appear after logged in? im not sure where is the error :/

**Comment by ig4e** [comment]
yah its appear after logged in

**Comment by Allvaa** [comment]
may check your lavalink ip port and pass? because I got your error on the nodes configuration
